version: '3.3'
services:
  mongodb:
    image: mongo:5.0-focal
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db_data:/data/db
  redis:
    image: redis:6.2.14-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./cache_data:/data/cache
  mongo_view:
    image: mongo-express:1.0-18-alpine3.18
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
  tracker:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DB_USER: admin
      DB_PASS: password
      DB_HOST: mongodb
      CACHE_HOST: redis
      CACHE_PORT: 6379
      # CACHE_EXPIRATION: 1800
      ETH_URL: https://eth-mainnet.public.blastapi.io
      METIS_URL: https://lb.nodies.app/v1/0fdd0b2f9bb84e8c85c3b81a94e2162e
      JWT_SECRET: xTC83d93GmPVkKitxTC83d93GmPVkKitxTC83d93GmPVkKit
      JWT_EXPIRY: 1d
volumes:
  db_data:
  cache_data:
